dist: trusty
language: generic
services:
- docker
env:
  global:
  - CWD=$TRAVIS_BUILD_DIR
  matrix:
  - |
    DOCKER_LOGIN='eval [[ -n $DOCKER_PASSWORD ]] && docker login -u $DOCKER_USERNAME --password-stdin <<<$DOCKER_PASSWORD || exit 0'
    DOCKER_REPO="ea31337/ea31337-libre:${TRAVIS_BRANCH//master/latest}"
    DOCKER_BUILD="docker build --build-arg UID=$UID --target ea31337-src -t ${DOCKER_REPO} ."
    DOCKER_COPY="docker run -v $CWD:/opt/workspace:rw ${DOCKER_REPO} cp -frv /opt/EA/*.ex? /opt/workspace"
    CMD="${DOCKER_LOGIN} && ${DOCKER_BUILD}; [[ $TRAVIS_PULL_REQUEST = false ]] || exit 0; $DOCKER_COPY; docker push $DOCKER_REPO"
    DEPLOY=1
matrix:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
cache:
  directories:
  - /var/lib/docker
before_install:
- ulimit -a && free -m
before_script:
- docker --version && docker info
- docker images
- test -n "$OPT_TRACE" && set -x || true
script:
- echo $CMD
- eval $CMD
after_script:
- set +x
- git diff
after_success:
after_failure:
before_deploy:
- ls -1
deploy:
  provider: releases
  api_key:
  - secure: xNMEGaI6r/R+1yponEaPvinkFnYv3xJLvzhiTzJEGzOgKaqiCYaRWgM5e448iaCJeOb+mxLWt2zwu9MlmfWHVWn5bC4ozDZRAkpcui6lKlFUdoNAnAdyZ5+lmLeu1Botja4EGb/XewpiCcwQAt5+/HH+v3xbozeSMxBCiO5p74xSA3cc2uzUHp+hHzNZ8tjUA8lr4DwuiGX+irwPxcCVTurlUH6EHFvMlTy2w0i7zElwgyOR0x4GL4YdbfuUdESzadr4IENrGETNAi9PwVsUixJqpsdBtfyeUuMiUR0pPHQgFHMEXVwLrh4VfFZRabamziYt1PAsxyVkHlvPWiu7ffeDSd87xCAuQYHHMmWKTo5FCR6fr9qQcVq36nEqZkQ0pvv9T2lm2i4CAqZWIQE+yWMByIVFuZLZejV4zhMYu6mFpUAhJMmKcrFimvLaYNSqMIZxE9XNhE3wXTjeWxr/7unBOjzuCR8MXMqv7SkfJdmhvFPOwdH2GfqBaqoSbq9f7Bt8czoAZZkjZcvXxKwQR33QjOUX5WYwOCFHfkIwEZ6VFZhw1dg01HXv8tq7GVpwpjHwJeFJS5HzdB40Eh/TKkio/pl1YgBF17ne7NNp0uaUlbeJ70iuh2iL5eRaBAZW/MDi9/w4ZSAPzeR22JOgwuaI2hUm2kDUyfJS7Ib8ZjE=
  file:
    - "*.ex?"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: EA31337/EA31337-Libre
    condition: "$DEPLOY = 1"
    tags: true
after_deploy:
- make clean
